id: PD4902010
initial_creation_type: ocr
source_metadata:
  volumes:
    142b79101ff0460186fdf719daee1424:
      base_file: v050.txt
      image_group_id: I1PD95895
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1666
      volume_number: 50
